# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  #schedule:
   # - cron: "*/5 * * * *"

jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        continue-on-error: false
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          record: false
